services:
  airflow-scheduler:
    chart_name: rover-airflow
    chart_branch: nanjunda
    branch: roche-demo_shet_havyaka_telugu
    commit: rngfd7b065a7d59df3a8a6439d964b5dd707b8393f49900
    registry: "911167902799.dkr.ecr.eu-west-2-car-op.amazonaws.com"
    repository: "processors/engines/kavyaaagowriijeevaa"
    image_tag: demo-1.0.0-184
    image_digest: sha256:f5bb1df34b78033ad10a37a487d17a14d584855d1a45858c6b1c3b4f6d0cda1c
    namespace: dev
    values_file: "env/dev.yaml"
  airflow-web:
    chart_name: rover-airflow
    chart_branch: main
    branch: roche-demo
    commit: fd7b065a7d59df3a8a6439d964b5dd707b8393f48800
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/engines/airflow"
    image_tag: demo-1.0.0-184
    image_digest: sha256:1ed5bdf5fbe2cde65435d2bddb7f8dc40d13c34f463b4ef82652debaffe2f260
    namespace: dev
    values_file: "env/dev.yaml"
  airflow-worker:
    chart_name: rover-airflow
    chart_branch: main
    branch: roche-demo
    commit: fd7b065a7d59df3a8a6439d964b5dd707b8393f47700
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/engines/airflow-worker"
    image_tag: demo-1.0.0-184
    image_digest: sha256:200fed74a1dfd46fb1054daf3ef143b28cd55d8e74db36785f53b27a82fc15ce
    namespace: dev
    values_file: "env/dev.yaml"
  auth-filter:
    chart_name: auth-filter
    chart_branch: kavyaaa
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d6600
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "internal-services/auth-filter"
    image_tag: 1.0.0-147
    image_digest: sha256:61e87fdf82011965ce42f2801b397e0ea7019dc8325bf2e6bde917273271dba9
    namespace: istio-system
    values_file: "values.yaml"
  auth:
    chart_name: rover-auth
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d5500
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "services/authentication"
    image_tag: 1.0.0-147
    image_digest: sha256:e3da75b070b5477deee67f0087ce74da8606a43be0a50e04e9980c135a1c7104
    namespace: dev
    values_file: "env/dev.yaml"
  backend:
    chart_name: "rover-backend"
    chart_branch: "RASH"
    branch: roche-demo
    commit: 0f9f9a2ce207f8d41fbee36d7c53bfc17ed493df7406209
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "services/backend"
    image_tag: demo-1.0.0-205
    image_digest: sha256:f76d42c53108a68ef5b3b053233e996bce52c28e341a878b5c7011b7c25312b3
    namespace: dev
    values_file: "env/dev.yaml"
  data-loader:
    chart_name: rover-data-loader
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "services/data-loader"
    image_tag: 1.0.0-147
    image_digest: sha256:871deb639487d76f6a5df543ecc9c2206af5875b5a5afd68541ab9f672722d29
    namespace: dev
    values_file: "env/dev.yaml"
  envelope-builder:
    chart_name: rover-envelope-builder
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/envelope-builder"
    image_tag: 1.0.0-147
    image_digest: sha256:279c1b3665dbcf8b420c4bcc8e068e844b346614bd1390e96123bf8c655230d2
    namespace: dev
    values_file: "env/dev.yaml"
  flows:
    chart_name: rover-flow
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f7406294545rash
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "services/flows-airflow"
    image_tag: 1.0.0-147
    image_digest: sha256:db31263f739f4a180de0ebad7372f151e9a87ae496119f74e34f9209d1fb4c7c
    namespace: dev
    values_file: "env/dev.yaml"
  gateway:
    chart_name: rover-gateway
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/services/gateway"
    image_tag: 1.0.0-147
    image_digest: sha256:f42ae4f6ebd33ad5aa7539c4cd1182638cc9fe8423f0672aa0ac4007049a5074
    namespace: dev
    values_file: "env/dev.yaml"
  jats-transformer:
    chart_name: rover-jats-transformer
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/jats-xhtml-transformer"
    image_tag: 1.0.0-147
    image_digest: sha256:691f40885040a26081622bb7921bc287e301223ea163565cb01af7f2ce071cce
    namespace: dev
    values_file: "env/dev.yaml"
  llm-query:
    chart_name: "rover-llm-query"
    chart_branch: main
    branch: roche-demo
    commit: 0f9f9a2ce207f8d41fbee36d7c53bfc17ed493df
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "services/llm-query-service"
    image_tag: demo-1.0.0-206
    image_digest: sha256:19b9be7b73e4c5396c013abf48125ae0d5d216ee9fc867e214002df862621634
    namespace: dev
    values_file: "env/dev.yaml"
  llm-triples-extraction:
    chart_name: rover-llm-triples-extraction
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/llm-triples-extraction"
    image_tag: 1.0.0-147
    image_digest: sha256:70d30f1b73a282756699825388431c0956b5dfa4e7518c2be1eccf8959331bc8
    namespace: dev
    values_file: "env/dev.yaml"
  metadata-filler:
    chart_name: rover-metadata-filler
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/document-metadata-filler"
    image_tag: 1.0.0-147
    image_digest: sha256:fb67c50c425dc31b5f80eb3ad48a29b42178f8513024f827e85d12f620ca7a1f
    namespace: dev
    values_file: "env/dev.yaml"
  message-handler:
    chart_name: rover-message-handler
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/services/message-handler"
    image_tag: 1.0.0-147
    image_digest: sha256:4c0aa56c4474dabf208857720e5dc309c8b5dc1c73371d878c7f436891ea1f1a
    namespace: dev
    values_file: "env/dev.yaml"
  ner-default:
    chart_name: rover-ner-default
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/ner-tagging"
    image_tag: 1.0.0-147
    image_digest: sha256:e4e8a4721e31a2a6ed3b4eabdec7a6464ba3173a9fe331f837327927951223db
    namespace: dev
    values_file: "env/dev.yaml"
  ner-generalized:
    chart_name: rover-ner-generalized
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/generalized-ner-tagger"
    image_tag: 1.0.0-147
    image_digest: sha256:f83110bbb4d69f915b6bf65bcce48dd10b81564f905afc7b3f0ead571e017601
    namespace: dev
    values_file: "env/dev.yaml"
  text-embeddings:
    chart_name: rover-text-embeddings
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/text-embeddings"
    image_tag: 1.0.0-147
    image_digest: sha256:8275fae06464bd47c67494ffb4a53577f7fb0b4da8cfcc415009994c3be22dad
    namespace: dev
    values_file: "env/dev.yaml"
  tika:
    chart_name: rover-tika
    chart_branch: main
    branch: ci_build_patch
    commit: 2f45981ef59a498b45967ee20b0382e8e5677602
    registry: "docker.io"
    repository: "apache/tika"
    image_tag: 2.9.2.1
    image_digest: sha256:82918563ec63d9726d39517b683dede3dfdf23f325de29605d562747e5d5bde9
    namespace: dev
    values_file: "env/dev.yaml"
  ui:
    chart_name: "rover-ui"
    chart_branch: "main"
    branch: roche-demo
    commit: 6d1930ae85e76335288567805ddca7583d093db4
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "ui/ui"
    image_tag: demo-1.0.0-208
    image_digest: sha256:c678ff89406ef287b539fbcc1270cce3b1c8f23e5234e9b367dfcafdad460edb
    namespace: dev
    values_file: "env/dev.yaml"
  xhtml-extractor:
    chart_name: rover-xhtml-extractor
    chart_branch: main
    branch: roche-demo
    commit: 75cc13f38d5d82e5f20c8d58c4c9f2b12c135b3d
    registry: "911167902799.dkr.ecr.eu-west-2.amazonaws.com"
    repository: "processors/catalogue/xhtml-extractor"
    image_tag: 1.0.0-147
    image_digest: sha256:b12adb63f5c91ba02f88bbdbca6f50ca2ec3a3365e07c8e852bff6ac586a0e4e
    namespace: dev
    values_file: "env/dev.yaml"
